-- Fix for "Could not find the table 'public.menu_categories' in the schema cache".
-- Run this in Supabase SQL Editor, then refresh /admin/menu.

create table if not exists public.menu_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table if exists public.menu
  add column if not exists category_order integer not null default 0,
  add column if not exists sort_order integer not null default 0;

insert into public.menu_categories (slug, name, sort_order, active)
values
  ('entradas', 'Entradas quentes', 0, true),
  ('frio', 'Entradas frias', 1, true),
  ('sashimi', 'Sashimis', 2, true),
  ('jyo', 'Jyos', 3, true),
  ('niguiri', 'Niguiris', 4, true),
  ('hot', 'Hot rolls', 5, true),
  ('temaki', 'Temakis', 6, true),
  ('yakissoba', 'Yakissoba', 7, true),
  ('executivo', 'Executivos', 8, true),
  ('poke', 'Pokes', 9, true),
  ('combinado', 'Combinados', 10, true),
  ('sobremesa', 'Sobremesas', 11, true),
  ('bebida', 'Bebidas', 12, true),
  ('drink', 'Drinks', 13, true),
  ('destilado', 'Destilados', 14, true)
on conflict (slug) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order,
  active = excluded.active;

insert into public.menu_categories (slug, name, sort_order, active)
select distinct
  menu.category,
  initcap(replace(menu.category, '-', ' ')),
  coalesce(min(menu.category_order), 999),
  true
from public.menu
where menu.category is not null and menu.category <> ''
group by menu.category
on conflict (slug) do nothing;

create index if not exists menu_categories_sort_order_idx
on public.menu_categories (sort_order);

alter table public.menu_categories enable row level security;

drop policy if exists "App can read menu categories" on public.menu_categories;
create policy "App can read menu categories"
on public.menu_categories for select
using (true);

drop policy if exists "App can insert menu categories" on public.menu_categories;
create policy "App can insert menu categories"
on public.menu_categories for insert
with check (true);

drop policy if exists "App can update menu categories" on public.menu_categories;
create policy "App can update menu categories"
on public.menu_categories for update
using (true)
with check (true);

drop policy if exists "App can delete menu categories" on public.menu_categories;
create policy "App can delete menu categories"
on public.menu_categories for delete
using (true);

grant select, insert, update, delete on table public.menu_categories to anon, authenticated;
grant usage, select on sequence public.menu_categories_id_seq to anon, authenticated;

notify pgrst, 'reload schema';
