-- Schema updates for Misso Sushi admin/checkout features.
-- Run in Supabase SQL Editor, or apply with an admin Postgres connection.

create table if not exists public.store_settings (
  id bigint generated by default as identity primary key,
  is_open boolean not null default true,
  average_time text not null default '35 a 50 min',
  service_fee numeric not null default 0,
  service_fee_label text not null default 'Taxa de embalagem',
  pickup_slot_minutes integer not null default 30,
  min_pickup_minutes integer not null default 35,
  max_advance_days integer not null default 1,
  order_slot_limit integer not null default 0,
  checkout_addons jsonb not null default '[
    { "id": "hashi", "name": "Hashi", "unit_price": 2.5, "active": true },
    { "id": "shoyu-extra", "name": "Shoyu extra", "unit_price": 2.5, "active": true },
    { "id": "gengibre", "name": "Gengibre", "unit_price": 2.5, "active": true }
  ]'::jsonb,
  business_hours jsonb not null default '{
    "0": { "label": "domingo", "open": "12:00", "close": "23:00" },
    "1": { "label": "segunda-feira", "open": "12:00", "close": "23:00" },
    "2": { "label": "terca-feira", "open": "12:00", "close": "23:00" },
    "3": { "label": "quarta-feira", "open": "12:00", "close": "23:00" },
    "4": { "label": "quinta-feira", "open": "12:00", "close": "23:00" },
    "5": { "label": "sexta-feira", "open": "12:00", "close": "00:00" },
    "6": { "label": "sabado", "open": "12:00", "close": "00:00" }
  }'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.store_settings (is_open, average_time, business_hours)
select true, '35 a 50 min', '{
  "0": { "label": "domingo", "open": "12:00", "close": "23:00" },
  "1": { "label": "segunda-feira", "open": "12:00", "close": "23:00" },
  "2": { "label": "terca-feira", "open": "12:00", "close": "23:00" },
  "3": { "label": "quarta-feira", "open": "12:00", "close": "23:00" },
  "4": { "label": "quinta-feira", "open": "12:00", "close": "23:00" },
  "5": { "label": "sexta-feira", "open": "12:00", "close": "00:00" },
  "6": { "label": "sabado", "open": "12:00", "close": "00:00" }
}'::jsonb
where not exists (select 1 from public.store_settings);

create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  description text not null default '',
  discount_type text not null default 'percent',
  discount_value numeric not null default 0,
  min_order_value numeric not null default 0,
  usage_limit integer,
  used_count integer not null default 0,
  starts_at timestamptz,
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.menu_categories (slug, name, sort_order, active)
values
  ('entradas', 'Entradas quentes', 0, true),
  ('frio', 'Entradas frias', 1, true),
  ('sashimi', 'Sashimis', 2, true),
  ('jyo', 'Jyos', 3, true),
  ('niguiri', 'Niguiris', 4, true),
  ('hot', 'Hot rolls', 5, true),
  ('temaki', 'Temakis', 6, true),
  ('yakissoba', 'Yakissoba', 7, true),
  ('executivo', 'Executivos', 8, true),
  ('poke', 'Pokes', 9, true),
  ('combinado', 'Combinados', 10, true),
  ('sobremesa', 'Sobremesas', 11, true),
  ('bebida', 'Bebidas', 12, true),
  ('drink', 'Drinks', 13, true),
  ('destilado', 'Destilados', 14, true)
on conflict (slug) do update
set name = excluded.name;

insert into public.menu_categories (slug, name, sort_order, active)
select distinct
  menu.category,
  initcap(replace(menu.category, '-', ' ')),
  coalesce(min(menu.category_order), 999),
  true
from public.menu
where menu.category is not null and menu.category <> ''
group by menu.category
on conflict (slug) do nothing;

alter table if exists public.menu
  add column if not exists active boolean not null default true,
  add column if not exists availability_status text not null default 'ativo',
  add column if not exists featured boolean not null default false;

alter table if exists public.orders
  add column if not exists note text,
  add column if not exists payment_method text,
  add column if not exists payment_status text not null default 'pendente',
  add column if not exists fulfillment text not null default 'retirada',
  add column if not exists fulfillment_type text not null default 'asap',
  add column if not exists scheduled_for timestamptz,
  add column if not exists addons jsonb not null default '[]'::jsonb,
  add column if not exists service_fee numeric not null default 0,
  add column if not exists service_fee_label text,
  add column if not exists coupon_redeemed_at timestamptz,
  add column if not exists mercado_pago_payment_id text,
  add column if not exists subtotal numeric not null default 0,
  add column if not exists discount_amount numeric not null default 0,
  add column if not exists coupon_code text,
  add column if not exists promotion_id bigint;

create index if not exists orders_payment_status_idx on public.orders (payment_status);
create index if not exists orders_mercado_pago_payment_id_idx on public.orders (mercado_pago_payment_id);
create index if not exists orders_coupon_code_idx on public.orders (coupon_code);
create index if not exists orders_scheduled_for_idx on public.orders (scheduled_for);
create index if not exists menu_availability_status_idx on public.menu (availability_status);
create index if not exists menu_categories_sort_order_idx on public.menu_categories (sort_order);

alter table if exists public.store_settings
  add column if not exists service_fee numeric not null default 0,
  add column if not exists service_fee_label text not null default 'Taxa de embalagem',
  add column if not exists pickup_slot_minutes integer not null default 30,
  add column if not exists min_pickup_minutes integer not null default 35,
  add column if not exists max_advance_days integer not null default 1,
  add column if not exists order_slot_limit integer not null default 0,
  add column if not exists checkout_addons jsonb not null default '[
    { "id": "hashi", "name": "Hashi", "unit_price": 2.5, "active": true },
    { "id": "shoyu-extra", "name": "Shoyu extra", "unit_price": 2.5, "active": true },
    { "id": "gengibre", "name": "Gengibre", "unit_price": 2.5, "active": true }
  ]'::jsonb;

alter table if exists public.promotions
  add column if not exists min_order_value numeric not null default 0,
  add column if not exists usage_limit integer,
  add column if not exists used_count integer not null default 0,
  add column if not exists starts_at timestamptz,
  add column if not exists expires_at timestamptz;

alter table if exists public.menu enable row level security;
alter table if exists public.orders enable row level security;
alter table if exists public.store_settings enable row level security;
alter table if exists public.promotions enable row level security;
alter table if exists public.menu_categories enable row level security;

drop policy if exists "Public can read active menu" on public.menu;
create policy "Public can read active menu"
on public.menu for select
using (active is distinct from false);

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
on public.orders for insert
with check (true);

drop policy if exists "Public can read store settings" on public.store_settings;
create policy "Public can read store settings"
on public.store_settings for select
using (true);

drop policy if exists "Public can read active promotions" on public.promotions;
create policy "Public can read active promotions"
on public.promotions for select
using (active is true);

drop policy if exists "Public can read active menu categories" on public.menu_categories;
create policy "Public can read active menu categories"
on public.menu_categories for select
using (active is true);
