-- Schema updates for Misso Sushi admin/checkout features.
-- Run in Supabase SQL Editor, or apply with an admin Postgres connection.

create table if not exists public.store_settings (
  id bigint generated by default as identity primary key,
  is_open boolean not null default true,
  average_time text not null default '35 a 50 min',
  business_hours jsonb not null default '{
    "0": { "label": "domingo", "open": "12:00", "close": "23:00" },
    "1": { "label": "segunda-feira", "open": "12:00", "close": "23:00" },
    "2": { "label": "terca-feira", "open": "12:00", "close": "23:00" },
    "3": { "label": "quarta-feira", "open": "12:00", "close": "23:00" },
    "4": { "label": "quinta-feira", "open": "12:00", "close": "23:00" },
    "5": { "label": "sexta-feira", "open": "12:00", "close": "00:00" },
    "6": { "label": "sabado", "open": "12:00", "close": "00:00" }
  }'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.store_settings (is_open, average_time, business_hours)
select true, '35 a 50 min', '{
  "0": { "label": "domingo", "open": "12:00", "close": "23:00" },
  "1": { "label": "segunda-feira", "open": "12:00", "close": "23:00" },
  "2": { "label": "terca-feira", "open": "12:00", "close": "23:00" },
  "3": { "label": "quarta-feira", "open": "12:00", "close": "23:00" },
  "4": { "label": "quinta-feira", "open": "12:00", "close": "23:00" },
  "5": { "label": "sexta-feira", "open": "12:00", "close": "00:00" },
  "6": { "label": "sabado", "open": "12:00", "close": "00:00" }
}'::jsonb
where not exists (select 1 from public.store_settings);

create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  description text not null default '',
  discount_type text not null default 'percent',
  discount_value numeric not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table if exists public.menu
  add column if not exists active boolean not null default true,
  add column if not exists availability_status text not null default 'ativo',
  add column if not exists featured boolean not null default false;

alter table if exists public.orders
  add column if not exists payment_status text not null default 'pendente',
  add column if not exists fulfillment text not null default 'retirada',
  add column if not exists mercado_pago_payment_id text;

create index if not exists orders_payment_status_idx on public.orders (payment_status);
create index if not exists orders_mercado_pago_payment_id_idx on public.orders (mercado_pago_payment_id);
create index if not exists menu_availability_status_idx on public.menu (availability_status);

alter table if exists public.menu enable row level security;
alter table if exists public.orders enable row level security;
alter table if exists public.store_settings enable row level security;
alter table if exists public.promotions enable row level security;

drop policy if exists "Public can read active menu" on public.menu;
create policy "Public can read active menu"
on public.menu for select
using (active is distinct from false);

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
on public.orders for insert
with check (true);

drop policy if exists "Public can read store settings" on public.store_settings;
create policy "Public can read store settings"
on public.store_settings for select
using (true);

drop policy if exists "Public can read active promotions" on public.promotions;
create policy "Public can read active promotions"
on public.promotions for select
using (active is true);
